dockerRegistry: "kubedb"
catalog:
  elasticsearch: true
  etcd: true
  memcached: true
  mongo: true
  mysql: true
  perconaxtradb: true
  pgbouncer: true
  postgres: true
  proxysql: true
  redis: true
